#define BLACK 2200
#define VERY_FAR 50
#define FAR 100
#define MEDIUM 300
#define CLOSE 500
#define CLAW 2
#define ELBOW 1
#define ARM 0
#define ARM_VERT 1700
#define ARM_DOWN 600
#define ARM_GROUND 0
#define ARM_GRAB 400 //NO CLUE IF THIS IS RIGHT
#define ARM_DROP 400 //NO CLUE IF THIS IS RIGHT
#define ARM_TUBE 400 //NO CLUE IF THIS IS RIGHT
#define ELBOW_TUBE 400 //NO CLUE IF THIS IS RIGHT
#define ELBOW_STRAIGHT 1300
#define ELBOW_GRAB 400 //NO CLUE IF THIS IS RIGHT
#define ELBOW_DROP 400 //NO CLUE IF THIS IS RIGHT
